const TopStoriesTypes = {
  FETCH_ASKSTORIES_FAILED: 'FETCH_ASKSTORIES_FAILED',
  FETCH_ASKSTORIES_START: 'FETCH_ASKSTORIES_START',
  FETCH_ASKSTORIES_SUCCESS: 'FETCH_ASKSTORIES_SUCCESS',
  INCREASE_CURRENT_PAGE: 'INCREASE_CURRENT_ASKPAGE',
};

export default TopStoriesTypes;
