const TopStoriesTypes = {
  FETCH_JOBSTORIES_FAILED: 'FETCH_JOBSTORIES_FAILED',
  FETCH_JOBSTORIES_START: 'FETCH_JOBSTORIES_START',
  FETCH_JOBSTORIES_SUCCESS: 'FETCH_JOBSTORIES_SUCCESS',
  INCREASE_CURRENT_JOBPAGE: 'INCREASE_CURRENT_JOBPAGE',
};

export default TopStoriesTypes;
