const TopStoriesTypes = {
  FETCH_TOPSTORIES_FAILED: 'FETCH_TOPSTORIES_FAILED',
  FETCH_TOPSTORIES_START: 'FETCH_TOPSTORIES_START',
  FETCH_TOPSTORIES_SUCCESS: 'FETCH_TOPSTORIES_SUCCESS',
  INCREASE_CURRENT_PAGE: 'INCREASE_CURRENT_PAGE',
};

export default TopStoriesTypes;
