const TopStoriesTypes = {
  FETCH_SHOWSTORIES_FAILED: 'FETCH_SHOWSTORIES_FAILED',
  FETCH_SHOWSTORIES_START: 'FETCH_SHOWSTORIES_START',
  FETCH_SHOWSTORIES_SUCCESS: 'FETCH_SHOWSTORIES_SUCCESS',
  INCREASE_CURRENT_PAGE: 'INCREASE_CURRENT_PAGE',
};

export default TopStoriesTypes;
