const TopStoriesTypes = {
  FETCH_NEWESTSTORIES_FAILED: 'FETCH_NEWESTSTORIES_FAILED',
  FETCH_NEWESTSTORIES_START: 'FETCH_NEWESTSTORIES_START',
  FETCH_NEWESTSTORIES_SUCCESS: 'FETCH_NEWESTSTORIES_SUCCESS',
  INCREASE_CURRENT_PAGE: 'INCREASE_CURRENT_PAGE',
};

export default TopStoriesTypes;
